# Generated by Django 4.2.28 on 2026-03-07 18:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageToPdfConversion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image_count', models.PositiveIntegerField(default=1)),
                ('original_filenames', models.JSONField(default=list, help_text='List of original filenames in order')),
                ('total_original_size_kb', models.PositiveIntegerField(help_text='Total size of all uploaded images in KB')),
                ('page_size', models.CharField(choices=[('A4', 'A4'), ('A3', 'A3'), ('LETTER', 'Letter'), ('LEGAL', 'Legal'), ('FIT', 'Fit to Image')], default='A4', max_length=10)),
                ('orientation', models.CharField(choices=[('portrait', 'Portrait'), ('landscape', 'Landscape')], default='portrait', max_length=10)),
                ('pdf_filename', models.CharField(default='converted.pdf', max_length=255)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='pdf_conversions/%Y/%m/%d/')),
                ('pdf_size_kb', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Image to PDF Conversion',
                'verbose_name_plural': 'Image to PDF Conversions',
                'ordering': ['-created_at'],
            },
        ),
    ]
