# Generated by Django 4.2.28 on 2026-03-07 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_file', models.FileField(upload_to='image_converter/original/%Y/%m/%d/')),
                ('original_filename', models.CharField(max_length=255)),
                ('original_format', models.CharField(choices=[('JPEG', 'JPG'), ('PNG', 'PNG'), ('WEBP', 'WEBP'), ('GIF', 'GIF'), ('BMP', 'BMP'), ('TIFF', 'TIFF')], max_length=10)),
                ('original_size_kb', models.PositiveIntegerField(help_text='Size in KB')),
                ('was_compressed', models.BooleanField(default=False)),
                ('compressed_size_kb', models.PositiveIntegerField(blank=True, null=True)),
                ('requested_format', models.CharField(choices=[('JPEG', 'JPG'), ('PNG', 'PNG'), ('WEBP', 'WEBP'), ('GIF', 'GIF'), ('BMP', 'BMP'), ('TIFF', 'TIFF')], max_length=10)),
                ('converted_file', models.FileField(blank=True, null=True, upload_to='image_converter/output/%Y/%m/%d/')),
                ('converted_size_kb', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Image Conversion',
                'verbose_name_plural': 'Image Conversions',
                'ordering': ['-created_at'],
            },
        ),
    ]
