server {
    listen 80;
    server_name _;

    # change the path if you used a different socket location
    location / {
        proxy_pass http://unix:/run/gunicorn.sock;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # serve static files directly
    location /static/ {
        alias /var/www/test-aws-be/test-aws-be/staticfiles/;
    }
}
